### ISSUE TITLE
TypeScript fork/demo/guidance

### ISSUE THREAD

**Issue by mattgi** [sw-yx/jamstack-hackathon-starter#10]
This repo has the stack that I crave, but I also want to use TypeScript.

Are you able to provide some guidance on how to set up a Gatsby project with Netlify Functions and Netlify Identity, but using TypeScript?

I cannot find a reference implementation in this space - or, if I can, the functions are "hello world" and when I go to add something non-trivial (like a dependency to mongodb) I can't find a solid build pipeline to appease the webpack/babel Gods so am not sure how to set it up.

A fork of this repo in TypeScript would be amazing.

**Comment by devuxer** [comment]
Hey @mattgi,

Did you ever figure this out?

**Comment by mattgi** [comment]
No. I had a half-baked build flow that worked, but it was a multi step process to first build the TS before using `netlify-lambda build`. I gave up and went with something different in the end.

**Comment by devuxer** [comment]
@mattgi , Ahh okay, thx for letting me know.

**Comment by swyxio** [comment]
did i not finish this?? lol i must have gotten distracted. i'm so sorry. wasnt a priority, and then i left netlify.

**Comment by devuxer** [comment]
@sw-yx , That's why I didn't tag you directly :)

If you have any tips, though, would be much appreciated!

**Comment by swyxio** [comment]
i mean, theres a lot details to handle. it just means knowing typescript well tbh. 

how bout you fork this project and convert it to TS, and i can help you wherever you get stuck? i dont have time to do this fully on my own unforuntaltey

**Comment by devuxer** [comment]
@sw-yx ,

Gotcha. Well, I'm much more comfortable using tsc than webpack/babel, so maybe I'll see if I can just spin my own build process that results in a my Gatsby project just having built js files in it. Think that makes sense?

**Comment by swyxio** [comment]
yeah thats fine. good luck. with time, try to get comfortable with webpack/babel, its annoying but just hard to avoid when dealing with toolchains in the wild unfortunately.

**Comment by devuxer** [comment]
@sw-yx, Thanks, and I hear you! Among many many things I need to get better at.
