### ISSUE TITLE
Hard refresh on client route returns 404, and broken component

### ISSUE THREAD

**Issue by fraserisland** [sw-yx/jamstack-hackathon-starter#11]
1. Log in
2. Click "Go to App (with Netlify Identity)"
3. Click "Profile"
3. Hard refresh
5. You will see this, and not be able to use the login component rendered (which shouldn't be showing anyway as i'm logged in): 
![Screen Shot 2019-09-05 at 11 03 59 am](https://user-images.githubusercontent.com/35257108/64303750-e132ed80-cfcc-11e9-8ef7-af01e94a799b.png)

**Comment by swyxio** [comment]
i think this was an issue based on the old identity widget i used. i have now updated the versions. can you please try again? reopen if still an issue, pr welcome

**Comment by fraserisland** [comment]
The logging out issue was fixed by adding initAuth() to app.js, as for the 404, that is an open issue in the gatsby plugin for [client-side-routes](https://github.com/gatsbyjs/gatsby/issues/16097), which you can make 'look' fixed by adding a title to the page

**Comment by fraserisland** [comment]
It's fixed in yours, the 404 is still there but that's not an issue with your site specifically. Thanks as well for the awesome work on this, and all your other identity related stuff, has really helped me heaps!

**Comment by swyxio** [comment]
aww shucks thank you!
