### ISSUE TITLE
Get Netlify Function to work when deployed to Netlify

### ISSUE THREAD

**Issue by tristpc** [sw-yx/jamstack-hackathon-starter#15]
I can get the Netlify Function to work locally but in Netlify get this message: errorMessage":"Cannot find module 'axios'". This despite axios being in token-hider's package.json.

I still get error if I change package.json to include these:-
 "prod": "npm run build && npm run build:lambda",
    "build:lambda": "netlify-lambda build functions"
After adjusting command in netlify.toml to "npm run prod", the following deploy error in Netlify results:-

Error: netlify-lambda Error: Function source folder (specified in netlify-lambda serve/build command) and publish folder (specified in netlify.toml) should be different. They are both set to /opt/build/repo/functions.This is a common mistake for people switching from Netlify Dev to netlify-lambda. For an easy fix, change your functions key inside netlify.toml to something else, like "functions-build".

If I then change functions key in netlify.toml as suggested, then just get 404 pages for the functions.

How to get the Netlify Function token-hider working both locally and in Netlify when deployed?
Thanks

**Comment by swyxio** [comment]
hard to tell without a repro. are you sure you need netlify-lambda? you may not need it. (see its docs)

**Comment by tristpc** [comment]
I was referring to other repos, for another Gatsby starter. Your repo works fine, both locally and after Netlify Deploy, whether or not the Deploy by Netlify button is clicked.

After studying your files, I found there is much in your starting repo which is not commented on in the README. This is a bit misleading if one does not use the deploy button. Here is what I believe must be included in a repo for Netlify Function to work:-

- Install gatsby-plugin-netlify-identity @reach/dialog @reach/tabs @reach/visually-hidden react-netlify-identity-widget gatsby-plugin-netlify-identity
- add devDep "netlify-lambda": "^1.6.3",
- add netlify.toml
- put function in functions-src folder
- Add to package.json this script:- "postinstall": "netlify-lambda install",
- add react-netlify-identity-widget in gatsby-config.js 

With all these inclusions the function worked in other repos after deploying to Netlify.

**Comment by swyxio** [comment]
ah ok. may need more work on docs. happy to take PR if you wanna help :)
