### ISSUE TITLE
Having trouble setting it up due to prettier issue

### ISSUE THREAD

**Issue by reForMatt** [sw-yx/jamstack-hackathon-starter#17]
npm install runs and fails with this error:

npm ERR! Could not install from "prettier --write "**/*.{js,jsx,json,md}"" as it does not contain a package.json file.

Could I get some help to get this repo working? I want to use this as a starting point for my project. Thanks!

**Comment by gbtobias** [comment]
No idea what is going on with this issue, but I deleted this line under devDependencies in package.json and deleted the package_lock.json file entirely.

"format": "prettier --write \"**/*.{js,jsx,json,md}\"",

Now I no longer get the error at deploy.

**Comment by swyxio** [comment]
oh dear i dont know how that got in there. must be merge conflict. i'll fix
