### ISSUE TITLE
request for documentation - install and run commands

### ISSUE THREAD

**Issue by renschler** [sw-yx/jamstack-hackathon-starter#3]
do I have to do anything else besides "gatsby develop" to get lambda functions to work locally? I installed this hackathon starter but I get an error when trying to hit the lambda thats on the main page.

`> [HPM] Error occurred while trying to proxy request hello from localhost:8000 to http://localhost:9000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

**Comment by renschler** [comment]
Ok got it working.

I ended up running `npm run develop` in one terminal window, and then `npm run start:lambda` in another.

It might be worthwhile (esp for beginners) if you added a section to the main README which describes how to install and run locally.

**Comment by swyxio** [comment]
wanna send in a PR? :)

**Comment by renschler** [comment]
would be my first :), will give it a shot after I read up on how to do it

**Comment by swyxio** [comment]
awesome!!!! just do it, no fear, i'll guide you if anythings wrong

**Comment by swyxio** [comment]
hey friends, i have just [released a big update](https://github.com/sw-yx/jamstack-hackathon-starter/commit/e5f732da9036fa121dc8dc12a665dd5b7776c815) to this starter. it should fix many problems. please have a look and open a new issue if anything is outstanding.
