### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by cbfrance** [sw-yx/jamstack-hackathon-starter#5]
I can successfully log in to the app section once but then `Hello undefined` and the username is blank (screenshot). 

If I refresh it goes back to `You are not logged in`.

Tested in latest FF and Chrome using the one-click deploy button on Netlify. I didn't change any defaults.

Thank you for your work on this demo! 👏  It is super helpful to understand. Appreciate any input to get it working again.

<img width="605" alt="screen shot 2019-01-14 at 11 41 55 pm" src="https://user-images.githubusercontent.com/7366/51165872-7030a100-1856-11e9-983d-edf7783063f7.png">

**Comment by cbfrance** [comment]
There seems to be a problem with `isLoggedIn()` which causes bad redirection — that's a relatively superficial problem — but also I'm seeing problems with the login screen not appearing, the login success message appearing slowly ("You are logged in" takes 20 seconds to appear), and sometimes just becoming nonresponsive with some 404s in the console for `https://sitename.netlify.com/app/login#access_token=....`. 

Logging in with email seems fine, but using Google or Github commonly fails for me.

(I understand that on localhost _only_ email works — but that's a known issue. I'm having trouble with the third-party methods in production.)

I'll post notes here if I get any further with my understanding.

**Comment by swyxio** [comment]
hey! thanks for reporting. i'm not clear why it might have broken but to be honest i also hadnt tested the one click deploy very much. i'm very short on time this week but if you are still exploring this then i can record a video for you next week to walk thru

**Comment by cbfrance** [comment]
Thanks! a video is not necessary, really just would like help confirming if oAuth with Google is flaky.

I’m pretty confident with Netlify, but confused by these timeouts and the “partial success” behavior I’m seeing.

**Comment by swyxio** [comment]
i honestly dont know - havent tried Google oAuth much specifically. all i aim to do here is to help people add netlify-identity-widget to their gatsby apps. if Google OAuth inside netlify-identity-widget is acting up, that's a lower level concern (just as in lower down the stack) than here. 

You can see a "pure" demo here: https://identity.netlify.com/. I just tried it and it seems to work fine. So I'm not sure where exactly any issues with Google auth might arise.

if this is critical for whatever you're building, check in with our support (https://www.netlify.com/support/) and they'll help determine if its our fault and if so fix it.

**Comment by mrispoli24** [comment]
Hey all, had the same problem tonight working through the tutorial but was able to fix it by modifying the login page a bit. Looks like the auth isn't being initialized properly so the widget does not fire. Also prettier doesn't like the unused `isLoggedIn` function on that page. In any event I modified it to this and all is well if anyone is wondering. Not sure why it works on the live netlify demo though for this.

```js
import React from 'react'
import { navigate } from 'gatsby'
import { handleLogin, initAuth } from './services/auth'

class Login extends React.Component {
  componentDidMount = () => {
    initAuth()
  }
  handleSubmit = () => handleLogin(user => navigate(`/app/profile`))
  render() {
    return (
      <>
        <h1>Log in</h1>
        <button onClick={this.handleSubmit}>log in</button>
      </>
    )
  }
}

export default Login
```

**Comment by swyxio** [comment]
i’m long overdue to update this demo with everything i have done recently (check out react-netlify-identify). thanks for the prompting.

**Comment by ajerni** [comment]
Clicking on the login button I only see the log in option in the pop up but no sign up option. In the youtube walkthroug there is sign-up as well. Any idea on how to fix this?

**Comment by swyxio** [comment]
hey friends, i have just [released a big update](https://github.com/sw-yx/jamstack-hackathon-starter/commit/e5f732da9036fa121dc8dc12a665dd5b7776c815) to this starter. it should fix many problems. please have a look and open a new issue if anything is outstanding.
